# Generated by Django 2.2.4 on 2021-02-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jon',
            new_name='Job',
        ),
    ]
