# Generated by Django 2.2.4 on 2021-03-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20210228_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
