# Generated by Django 2.2.4 on 2021-03-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_auto_20210228_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='urls',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
